### PR TITLE
Formatting black+isort

### PR DESCRIPTION
**Pull request by dbrakenhoff**

### CODE REVIEW

**Comment by mbakker7** [comment]
Looks like `from tqdm.auto import trange` doesn't run. Should `tqdm` be listed as a dependency?

**Comment by dbrakenhoff** [comment]
Ah, I accidentally left the tqdm stuff in there.

We could add it as a dependency and use it as a progressbar for anything that takes a while? But that should be a separate PR so removing it from here. 

I'll submit the pyproject.toml and modify the CI in another PR.

**Comment by mbakker7** [comment]
Looks good. Ready to merge?

**Comment by mbakker7** [comment]
> Ah, I accidentally left the tqdm stuff in there.
> 
> We could add it as a dependency and use it as a progressbar for anything that takes a while? But that should be a separate PR so removing it from here.
> 
> I'll submit the pyproject.toml and modify the CI in another PR.

Sounds good. Looking forward to another PR.

**Pull request merged**
