### PR TITLE
Move to Github Actions

### PR DESCRIPTION
**Pull request by dbrakenhoff**

### CODE REVIEW

**Comment by dbrakenhoff** [comment]
@mbakker7 there are some undefined methods/variables in `circinhom.py` which is causing the flake8 check to fail.
Should these be fixed? Or should I ignore the file for now?

**Comment by mbakker7** [comment]
circinhom is not operational yet.
you can ignore the file for now (but obviously keep it)

**Comment by mbakker7** [comment]
Ready to merge?

**Comment by dbrakenhoff** [comment]
Yes!

**Pull request merged**
