### PR TITLE
Update master for release v0.6.6

### PR DESCRIPTION
**Pull request by mbakker7**

### CODE REVIEW

**Comment by dbrakenhoff** [comment]
Using this PR to make a new release for TTim. 

- [ ] Merge #58 
- [ ] Organize pumping test notebooks in docs into new and old.
- [ ] Anything else?

**Review by dbrakenhoff — APPROVED** [review]

**Review by dbrakenhoff — APPROVED** [review]

**Comment by dbrakenhoff** [comment]
@mbakker7, all good to go?

**Comment by mbakker7** [comment]
Looks good. Only improvement I am wondering about is the cross-sectional figures in the pumping test notebooks. There is a nice figure in, for example, the Oude Korendijk notebook with. a cross-section of the aquifer. The code for this figure is also shown in the notebook, but the code is exceedingly long (several screens). Any way we can hide the code of this cell in ReadTheDocs?

**Comment by dbrakenhoff** [comment]
Let's move the code for creating the cross sections to a separate file and call it from there. I'll make the change.

**Comment by mbakker7** [comment]
That worked! Code cell is hidden in Oude Korendijk. You're gonna have to tell me how you did that. 
Ready to merge.

**Comment by dbrakenhoff** [comment]
Add the cell tag "hide-input" to the cell metadata. I believe you can edit cell metadata in Jupyter Lab through a separate small window somehow. In VS Code you can use the  "Add cell tag"-command and then type "hide-input". 

This is what it looks like in JSON:

```json
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "tags": [
     "hide-input"
    ]
   },
   "outputs": [
    {
     "data": {
        "<output here>"
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "<python code here>"
   ]
  },
``

**Pull request merged**
